# action.yml
name: 'Giphy PR Comment'
description: 'Add a Giphy GIF comment to new pull requests.'
inputs:
  github-token:  # id of input
    description: 'GitHub Token'
    required: true
  giphy-api-key:
    description: 'Giphy API Key'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.giphy-api-key }}
branding:
  icon: 'zap' # Choose an Octicon icon name
  color: 'pink' # Choose a color name or hex code
